<?php

namespace Machouille\Site\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChewingGumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChewingGumRepository extends EntityRepository
{
	public function findArray($array){
		$qb = $this->createQueryBuilder('u')
					->Select('u')
					->Where('u.reference IN (:array)')
					->setParameter('array', $array);
		return $qb->getQuery()->getResult();
	}
}
